version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/login-workflow'
      schedule:
          interval: 'monthly'
          day: 'wednesday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'

    - package-ecosystem: 'npm'
      directory: '/login-workflow/example'
      schedule:
          interval: 'monthly'
          day: 'wednesday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
