# - "::login-workflow/"     # move root   e.g., "path/" => "after/path/" leaving this here for now, it might need turned on later
coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true