name: Lint Check
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "*/*"
permissions:
  pull-requests: write
jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
