name: Lint Check
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "*/*"

permissions:
  pull-requests: write

env:
  NODE_VERSION: 16
  
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn
      - name: Code Linting
        run: yarn lint
